service: federal-budget-dashboard

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  timeout: 30
  memorySize: 512
  
  # VPC Configuration for RDS access
  # REQUIRED: Update these with your actual VPC/subnet/security group IDs
  vpc:
    securityGroupIds:
      - sg-xxxxxxxxxxxxxxxx  # Replace with Lambda security group ID
    subnetIds:
      - subnet-xxxxxxxxxxxxxxxx  # Replace with private subnet ID
      - subnet-yyyyyyyyyyyyyyyy  # Replace with another private subnet ID (different AZ)
  
  environment:
    DB_SECRET_NAME: federal-budget-db-credentials-${self:provider.stage}
    AWS_REGION: ${self:provider.region}
    CORS_ORIGINS: ${env:CORS_ORIGINS, ''}
    DATABASE_DEBUG: ${env:DATABASE_DEBUG, 'false'}
  
  iam:
    role:
      statements:
        # Secrets Manager permissions
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: 
            - arn:aws:secretsmanager:${self:provider.region}:*:secret:federal-budget-db-credentials-${self:provider.stage}*
        
        # VPC permissions (auto-generated by serverless framework)
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
            - ec2:AttachNetworkInterface
            - ec2:DetachNetworkInterface
          Resource: "*"

functions:
  api:
    handler: app.main.lambda_handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false

# Resources for RDS and Secrets Manager (optional - can be created manually)
# resources:
#   Resources:
#     BudgetDatabase:
#       Type: AWS::RDS::DBInstance
#       Properties:
#         DBInstanceIdentifier: federal-budget-db-${self:provider.stage}
#         DBInstanceClass: db.t3.micro
#         Engine: postgres
#         EngineVersion: '15.4'
#         MasterUsername: budgetuser
#         MasterUserPassword: !Ref DatabasePassword
#         AllocatedStorage: 20
#         StorageType: gp2
#         VPCSecurityGroups:
#           - !Ref DatabaseSecurityGroup
#         DBSubnetGroupName: !Ref DatabaseSubnetGroup
#         BackupRetentionPeriod: 7
#         DeletionProtection: false 