service: federal-budget-dashboard

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  timeout: 30
  memorySize: 512
  
  # No VPC configuration needed for SQLite
  # SQLite runs locally within Lambda - much simpler!
  
  environment:
    CORS_ORIGINS: ${env:CORS_ORIGINS, ''}
    DATABASE_DEBUG: ${env:DATABASE_DEBUG, 'false'}
  
  # No special IAM permissions needed for SQLite
  # Lambda has basic execution role by default

functions:
  api:
    handler: app.main.lambda_handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false

# Resources for RDS and Secrets Manager (optional - can be created manually)
# resources:
#   Resources:
#     BudgetDatabase:
#       Type: AWS::RDS::DBInstance
#       Properties:
#         DBInstanceIdentifier: federal-budget-db-${self:provider.stage}
#         DBInstanceClass: db.t3.micro
#         Engine: postgres
#         EngineVersion: '15.4'
#         MasterUsername: budgetuser
#         MasterUserPassword: !Ref DatabasePassword
#         AllocatedStorage: 20
#         StorageType: gp2
#         VPCSecurityGroups:
#           - !Ref DatabaseSecurityGroup
#         DBSubnetGroupName: !Ref DatabaseSubnetGroup
#         BackupRetentionPeriod: 7
#         DeletionProtection: false 